# App Engine 配置文件
# Next.js 应用部署到 App Engine Standard Environment

runtime: nodejs20
env: standard

# 服务配置
service: default

# 实例类配置
instance_class: F2

# 自动扩缩配置
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# 环境变量
env_variables:
  NODE_ENV: production

# 处理程序配置
handlers:
  # 静态文件处理
  - url: /_next/static
    static_dir: .next/static
    secure: always
    
  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico
    secure: always
    
  - url: /.*\.(png|jpg|jpeg|gif|ico|svg|webp)
    static_files: public/\1
    upload: public/.*\.(png|jpg|jpeg|gif|ico|svg|webp)
    secure: always
    
  # 所有其他请求交给 Next.js 处理
  - url: /.*
    script: auto
    secure: always

# 跳过不需要的文件
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.log$
  - ^(.*/)?.*\.lock$
  - ^(.*/)?package-lock\.json$
  - ^(.*/)?yarn\.lock$