# Cloud Build 配置文件示例
# 使用分离的环境变量配置Firebase服务账户

steps:
  # 构建步骤
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      # Firebase配置
      - 'FIREBASE_CONFIG=${_FIREBASE_CONFIG}'
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}'
    secretEnv: ['FIREBASE_PRIVATE_KEY']
    
  # 部署步骤
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
    env:
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}'
    secretEnv: ['FIREBASE_PRIVATE_KEY']

# 声明加密的环境变量
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/firebase-private-key/versions/latest
      env: 'FIREBASE_PRIVATE_KEY'

# 替换变量（在触发器中配置）
substitutions:
  _FIREBASE_CONFIG: 'your-firebase-config'
  _FIREBASE_PROJECT_ID: 'your-project-id'
  _FIREBASE_CLIENT_EMAIL: 'your-service-account@your-project.iam.gserviceaccount.com'
  
# 构建选项
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
# 超时设置
timeout: '1200s'