# Cloud Build 配置文件
# 使用 Secret Manager 管理 Firebase 配置

steps:
  # 构建步骤
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_PROJECT_ID}'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_API_KEY}'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_AUTH_DOMAIN}'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_STORAGE_BUCKET}'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_SENDER_ID}'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_APP_ID}'
      - 'NEXT_PUBLIC_FIREBASE_DATABASE_URL=${_DATABASE_URL}'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_MEASUREMENT_ID}'
    secretEnv: ['_PROJECT_ID', '_API_KEY', '_AUTH_DOMAIN', '_STORAGE_BUCKET', '_SENDER_ID', '_APP_ID', '_DATABASE_URL', '_MEASUREMENT_ID']
    
  # 部署步骤
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    env:
      - 'FIREBASE_CONFIG=${_FIREBASE_CONFIG}'
      - 'FIREBASE_CLIENT_EMAIL=${_CLIENT_EMAIL}'
      - 'FIREBASE_PRIVATE_KEY=${_PRIVATE_KEY}'
    secretEnv: ['_FIREBASE_CONFIG', '_CLIENT_EMAIL', '_PRIVATE_KEY']

# Secret Manager 配置
availableSecrets:
  secretManager:
    # Firebase 客户端配置
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: '_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: '_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: '_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: '_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: '_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: '_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_DATABASE_URL/versions/latest
      env: '_DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest
      env: '_MEASUREMENT_ID'
    # Firebase 服务端配置
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_CONFIG/versions/latest
      env: '_FIREBASE_CONFIG'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_CLIENT_EMAIL/versions/latest
      env: '_CLIENT_EMAIL'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PRIVATE_KEY/versions/latest
      env: '_PRIVATE_KEY'
  
# 构建选项
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
# 超时设置
timeout: '1200s'