# Cloud Build 配置文件示例
# 展示如何使用Base64编码的Firebase服务账户

steps:
  # 构建步骤
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      # 普通配置
      - 'FIREBASE_CONFIG=${_FIREBASE_CONFIG}'
      # Base64编码的服务账号（从Secret Manager获取）
      - 'FIREBASE_SERVICE_ACCOUNT_BASE64=${_FIREBASE_SERVICE_ACCOUNT_BASE64}'
    secretEnv: ['FIREBASE_SERVICE_ACCOUNT_BASE64']
    
  # 部署步骤
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
    env:
      - 'FIREBASE_SERVICE_ACCOUNT_BASE64=${_FIREBASE_SERVICE_ACCOUNT_BASE64}'
    secretEnv: ['FIREBASE_SERVICE_ACCOUNT_BASE64']

# 声明加密的环境变量
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/firebase-service-account/versions/latest
      env: 'FIREBASE_SERVICE_ACCOUNT_BASE64'

# 替换变量（在触发器中配置）
substitutions:
  _FIREBASE_CONFIG: 'your-firebase-config'
  
# 构建选项
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
# 超时设置
timeout: '1200s'