# Cloud Build 配置文件示例
# 使用分离的环境变量配置Firebase服务账户

steps:
  # 构建步骤
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      # Firebase配置（客户端）
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - 'NEXT_PUBLIC_FIREBASE_DATABASE_URL=${_NEXT_PUBLIC_FIREBASE_DATABASE_URL}'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}'
      # Firebase配置（服务端）
      - 'FIREBASE_CONFIG=${_FIREBASE_CONFIG}'
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}'
      - 'FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY}'
    
  # 部署步骤
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'deploy']
    env:
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}'
      - 'FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY}'

# 替换变量（在触发器中配置）
substitutions:
  # Firebase客户端配置
  _NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyCIQbFi0ogL2uAyRmAqeKn7iNGpun3AFfY'
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'perceptive-map-465407-s9.firebaseapp.com'
  _NEXT_PUBLIC_FIREBASE_DATABASE_URL: 'https://perceptive-map-465407-s9-default-rtdb.firebaseio.com'
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'perceptive-map-465407-s9'
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'perceptive-map-465407-s9.firebasestorage.app'
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '383688111435'
  _NEXT_PUBLIC_FIREBASE_APP_ID: '1:383688111435:web:948c86bc46b430222224ce'
  _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: 'G-90M1DVZKQT'
  # Firebase服务端配置
  _FIREBASE_CONFIG: '{"projectId":"perceptive-map-465407-s9","authDomain":"perceptive-map-465407-s9.firebaseapp.com","storageBucket":"perceptive-map-465407-s9.appspot.com"}'
  _FIREBASE_PROJECT_ID: 'perceptive-map-465407-s9'
  _FIREBASE_CLIENT_EMAIL: 'firebase-adminsdk-fbsvc@perceptive-map-465407-s9.iam.gserviceaccount.com'
  _FIREBASE_PRIVATE_KEY: '-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCrOvf64lvWvY1n\nDVKFA/pZU4EWW6A06XKRl90ol4znHMK3zYZiBrlWMGkiBGNNKxVcmDTB5MhmxPMO\nqtcR+04vPbzf4lveHhGqzKj9TQ+KkmQdZIQKOGIQAPCoNyWlwzqmzidJQXfKenGL\nDKdhucC5VuaIEDNh38Kvx4Vx0Sv5Y2ZBgcJ78Mcqr6NA6RTAfH+J9brKrdQNGRqi\nYEvoL0yKYo709VW8k6Qr/T2H0cxMnMoqVD2BivfEMf9DBrLmxBrrdgh+JJmQNDJX\nmyrwliJy62YrbFpmHY3KugLXZOozpU5Zx4F2UvMmHFuBtYFjaW9B7U99DvXeaPp1\nYDs13LZJAgMBAAECggEABHSP1v1zst93zampNcWbVKVPWJPfEKxVLpT+p1g7nlu7\n+0xKlrZswrJg4Dxs8IDLnF11YwPxvcnCyter0lmqiV0+9IVNnb1tIZJyQ7uFO6jH\naTMB5a3da1Zkm80mshHAjUXeFwgBB5dMzgUtjrZ6yT6DDfjM48b6eQeDZI5o8CnR\n4bbXc4gqAeVW2shiKfmpDjFVueWqDC2P+32JnPWArsdK0yGNpTPKWydTz8mebIqz\n/hz+sXC68LiRrW2f/4eRe9Sbgrq8o4tvSGHJNhbZFMkOYa87EUaimf2JaJgZ9Lvb\nGQGVv6GXyg0BBSoNlUk+fFbMHtEVWhvvr85Y7uveywKBgQDtxclYSox9YX0TZr8D\nh0PLi6DKhh+/srYICN+pNY7yzoqCt1xhSEs4FXZ7W4JOtR0uJd7IRyODsBCz+SDh\nYsfbKESN01VEQISpG7t4ZjEVxOlM1aO6fnd9zCpixelAQegfiPYMmqc00IgBEq2I\nlpNeAnBhPRtCDqacF4LOJXfoMwKBgQC4W0+gOcD6IpzOMwTTB4pZ4n/7RGfQSm/5\npqvJ/+ds94fUYK+bKYGWcZbzGs/AzudJLvdOaBnsaWl05coflNtLYn+juDF0zaZh\nb0MG9SotuA7PllMqLHV1uqzvSZLDirGtF5lJeIxnIRAEwfwA8WPeJjhulxjXUapn\nIOGP4GcbkwKBgEXl+RTNhZNuT1iewdSFtTZnK7OdzkOKg9zEzwttRUK32RwoTy4C\nFKq+FICbHCmLMLLaSy3RS+1wmthtim73nQ0eP1j6IXzZAqa8ElaIpDFkG7mMrH8s\nonAGzwcOa02KknSCzOJTrIfoLbMzDHS030mpqePMFPFMYUpN1xRHC4LlAoGAbAlm\nwljWFEAQcG5Jl3nFxCMOKSvPQqs8r6rS5Y/ICX2N5hG7F0zdmlJ6yYCe2zjlJWgW\nmaY7+uVTXaQELTnIwYa5kjIxGWgi5tqTBxLJYv2IAHLxzbc8Jn/9NEWDcoBm2y8H\nL50reoxPnNopWkwb4GW5kGWPsy8ykzkbtnslMW0CgYA19xFDdQPJasCsm7oZj2yD\nc045Pz/nZuAqJ1FO7LEvZMtCoFNkHdZDaQSvXggxW1fIgfsMuoRuaOSREXR5Yqbe\n7DHpYhPhOgppfgRxicCgsNMbU/3Wv/Sgpox9QRg1J3UjPBrDpXgMeWHFIHeCN25y\nobMb8a8ktwLhbXaF1Prkrw==\n-----END PRIVATE KEY-----'
  
# 构建选项
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
# 超时设置
timeout: '1200s'